FROM python:3.11

RUN mkdir /microservice

WORKDIR /microservice

COPY requirements.txt /microservice/
RUN pip install -r requirements.txt

COPY Predictor.py   model.pkl /microservice/

CMD seldon-core-microservice $MODEL_NAME --service-type $SERVICE_TYPE --grpc-port ${GRPC_PORT} --metrics-port ${METRICS_PORT} --http-port ${HTTP_PORT}
