# apiVersion: eks.amazonaws.com/v1
# kind: NodeClass
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: automode-default-nc
spec:

  role: "eks-auto-node-role"

  # Required: Subnet selection for node placement
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "private"
    # Alternative using direct subnet ID
    # - id: "subnet-0123456789abcdef0"

  # Required: Security group selection for nodes
  securityGroupSelectorTerms:
    - tags:
        aws:eks:cluster-name: "cjhyun-mlops"
    # Alternative approaches:
    # - id: "sg-0123456789abcdef0"
    # - name: "eks-cluster-node-security-group"

  # Optional: Configure SNAT policy (defaults to Random)
  snatPolicy: Random  # or Disabled

  # Optional: Network policy configuration (defaults to DefaultAllow)
  networkPolicy: DefaultAllow  # or DefaultDeny

  # Optional: Network policy event logging (defaults to Disabled)
  networkPolicyEventLogs: Disabled  # or Enabled

  # Optional: Configure ephemeral storage (shown with default values)
  ephemeralStorage:
    size: "80Gi"    # Range: 1-59000Gi or 1-64000G or 1-58Ti or 1-64T
    iops: 3000      # Range: 3000-16000
    throughput: 125 # Range: 125-1000

  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2 # This is changed to disable IMDS access from containers not on the host network
    httpTokens: required

  # Optional: Additional EC2 tags
  tags:
    Name: eks-auto/automode-default
    auto-delete: "no"
    eks:kubernetes-node-class-name: automode-default-nc
    eks:kubernetes-node-pool-name: automode-default-np
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: automode-default-np
spec:
  template:
    spec:
      nodeClassRef:
        # group: eks.amazonaws.com
        # kind: NodeClass
        group: karpenter.k8s.aws/v1
        kind: EC2NodeClass
        name: automode-default-nc

      requirements:
        - key: eks.amazonaws.com/instance-category
          operator: In
          values: ["c", "m", "r", "t"]
        - key: eks.amazonaws.com/instance-generation
          operator: Gt
          values: ["5"]
        - key: "eks.amazonaws.com/instance-hypervisor"
          operator: In
          values: ["nitro", "xen"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["ap-northeast-2a", "ap-northeast-2b", "ap-northeast-2c", "ap-northeast-2d"]

      expireAfter: "11000h"

  limits:
    cpu: "2000"
    memory: 2000Gi