apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: opendatahub-operator
  namespace: operators
spec:
  channel: stable
  # subscription dosen't work in opendatahub-operator.v1.5.0, so Automatic updates need to be changed to 'Manual'
  # and please approve manually through following commands
  # kubectl patch installplans -n operators install-fgrvs -p '{"spec":{"approved":true}}' --type merge
  installPlanApproval: Manual # Automatic
  name: opendatahub-operator
  source: community-operators-redhat
  sourceNamespace: olm
  startingCSV: opendatahub-operator.v1.1.1